import { readFile } from "node:fs/promises";
import path from "node:path";
import { jsPDF } from "jspdf";
import sharp from "sharp";
import { drawLineChart, drawRadarChart, SKINFIT_REPORT_THEME } from "./charts";
import { reportQrDataUrl } from "./qrCode";
import type { SdetectReportData } from "./types";

type LogoAsset = { dataUrl: string; displayW: number; displayH: number };

let logoCache: LogoAsset | null = null;

const LOGO_DISPLAY_H = 36;
/** Embed ~4× display size so jsPDF scales down crisply. */
const LOGO_RASTER_H = LOGO_DISPLAY_H * 4;

/** Vector SVG on light header — rasterized at high DPI for sharp PDF output. */
async function loadHeaderLogo(): Promise<LogoAsset> {
  if (logoCache) return logoCache;

  const svgPath = path.join(process.cwd(), "public/branding/skinfit-wellness-logo.svg");
  const wellnessPng = path.join(process.cwd(), "public/branding/skinfit-wellness-logo.png");

  let raster: Buffer;
  try {
    raster = await sharp(svgPath)
      .resize({ height: LOGO_RASTER_H })
      .png({ compressionLevel: 6 })
      .toBuffer();
  } catch {
    const buffer = await readFile(wellnessPng);
    raster = await sharp(buffer)
      .resize({ height: LOGO_RASTER_H, kernel: sharp.kernel.lanczos3 })
      .png({ compressionLevel: 6 })
      .toBuffer();
  }

  const meta = await sharp(raster).metadata();
  const aspect = (meta.width ?? 248) / (meta.height ?? LOGO_RASTER_H);
  const displayW = Math.round(LOGO_DISPLAY_H * aspect);

  logoCache = {
    dataUrl: `data:image/png;base64,${raster.toString("base64")}`,
    displayW,
    displayH: LOGO_DISPLAY_H,
  };
  return logoCache;
}

async function imageDataUrl(buffer: Buffer): Promise<string> {
  const jpg = await sharp(buffer).jpeg({ quality: 90 }).toBuffer();
  return `data:image/jpeg;base64,${jpg.toString("base64")}`;
}

function wrap(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text.replace(/\s+/g, " ").trim(), maxWidth);
}

function paintPageBackground(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...SKINFIT_REPORT_THEME.pageBg);
  doc.rect(0, 0, w, h, "F");
}

function drawCard(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  radius = 8
) {
  doc.setFillColor(...SKINFIT_REPORT_THEME.card);
  doc.setDrawColor(...SKINFIT_REPORT_THEME.navyLight);
  doc.setLineWidth(0.75);
  doc.roundedRect(x, y, w, h, radius, radius, "FD");
}

function drawHeader(
  doc: jsPDF,
  logo: LogoAsset,
  title: string,
  pageNo: number,
  total: number
) {
  const w = doc.internal.pageSize.getWidth();
  const headerH = 56;

  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, w, headerH, "F");
  doc.setDrawColor(...SKINFIT_REPORT_THEME.navy);
  doc.setLineWidth(2);
  doc.line(0, headerH, w, headerH);

  doc.addImage(logo.dataUrl, "PNG", 24, 10, logo.displayW, logo.displayH);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text(title, w / 2, 32, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
  doc.text(`${pageNo} / ${total}`, w - 24, 32, { align: "right" });
}

function drawFooter(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
  doc.text(
    "Clinical reference only · Generated by SkinFit Wellness",
    w / 2,
    h - 14,
    { align: "center" }
  );
}

function drawMetricCell(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string,
  showDivider: boolean
) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
  doc.text(label, x + w / 2, y + 14, { align: "center" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text(value, x + w / 2, y + 36, { align: "center" });
  if (showDivider) {
    doc.setDrawColor(...SKINFIT_REPORT_THEME.grid);
    doc.setLineWidth(0.5);
    doc.line(x + w, y + 8, x + w, y + h - 8);
  }
}

async function drawPageOne(
  doc: jsPDF,
  data: SdetectReportData,
  pageW: number,
  pageH: number,
  margin: number
) {
  const gutter = 18;
  const contentTop = 68;
  const contentBottom = pageH - 28;
  const leftW = Math.floor((pageW - margin * 2 - gutter) * 0.46);
  const rightX = margin + leftW + gutter;
  const rightW = pageW - margin - rightX;
  const leftX = margin;

  // ── Patient card ──
  const patientH = 52;
  drawCard(doc, leftX, contentTop, leftW, patientH);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Patient details", leftX + 14, contentTop + 16);

  const rowY = contentTop + 28;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...SKINFIT_REPORT_THEME.ink);
  const pad = 14;
  const colW = (leftW - pad * 2) / 3;
  const cols = [0, 1, 2].map((i) => leftX + pad + colW * i);

  const fitPatientText = (text: string, col: number, row: number) => {
    const maxW = colW - 6;
    let line = text;
    while (line.length > 1 && doc.getTextWidth(line) > maxW) {
      line = `${line.slice(0, -2)}…`;
    }
    doc.text(line, cols[col], rowY + row * 14);
  };

  fitPatientText(`Name: ${data.patient.name}`, 0, 0);
  fitPatientText(`Gender: ${data.patient.gender}`, 1, 0);
  fitPatientText(`Age: ${data.patient.age}`, 2, 0);
  fitPatientText(`Phone: ${data.patient.phone}`, 0, 1);
  fitPatientText(`Date: ${data.patient.reportDate}`, 1, 1);
  fitPatientText(`Scans: ${data.patient.scanFrequency}`, 2, 1);

  // ── Summary + QR ──
  const summaryY = contentTop + patientH + 12;
  const summaryH = 72;
  drawCard(doc, leftX, summaryY, leftW, summaryH);

  const qrSize = 56;
  const qrReserve = data.sourceReportUrl ? qrSize + 24 : 0;
  const metricsW = leftW - qrReserve;
  const cellW = metricsW / 3;

  drawMetricCell(doc, leftX, summaryY, cellW, summaryH, "Skin type", data.classification, true);
  drawMetricCell(
    doc,
    leftX + cellW,
    summaryY,
    cellW,
    summaryH,
    "Moisture",
    `${data.moisture}%`,
    true
  );
  drawMetricCell(
    doc,
    leftX + cellW * 2,
    summaryY,
    cellW,
    summaryH,
    "Overall score",
    String(data.comprehensiveScore),
    false
  );

  if (data.sourceReportUrl) {
    const qrX = leftX + leftW - qrSize - 12;
    const qrY = summaryY + (summaryH - qrSize) / 2 - 4;
    const qrDataUrl = await reportQrDataUrl(data.sourceReportUrl);
    doc.addImage(qrDataUrl, "PNG", qrX, qrY, qrSize, qrSize);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6);
    doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
    doc.text("Original report", qrX + qrSize / 2, summaryY + summaryH - 8, {
      align: "center",
    });
  }

  // ── Face captures ──
  const facesY = summaryY + summaryH + 12;
  const facesH = contentBottom - facesY;
  drawCard(doc, leftX, facesY, leftW, facesH);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Face captures", leftX + 14, facesY + 16);

  if (data.faceImages) {
    const pad = 14;
    const titleH = 22;
    const imgAreaY = facesY + titleH + 4;
    const imgAreaH = facesH - titleH - pad - 8;
    const imgGap = 10;
    const slotW = (leftW - pad * 2 - imgGap * 2) / 3;
    const imgH = imgAreaH - 16;
    const imgW = slotW - 8;

    const labels: Array<[keyof typeof data.faceImages, string]> = [
      ["front", "Front · white map"],
      ["left", "Left · natural"],
      ["right", "Right · natural"],
    ];

    for (let i = 0; i < labels.length; i++) {
      const [key, label] = labels[i];
      const slotX = leftX + pad + i * (slotW + imgGap);
      const dataUrl = await imageDataUrl(data.faceImages[key]);
      doc.setFillColor(...SKINFIT_REPORT_THEME.pageBg);
      doc.setDrawColor(...SKINFIT_REPORT_THEME.grid);
      doc.roundedRect(slotX, imgAreaY, slotW, imgH + 14, 4, 4, "FD");
      doc.addImage(dataUrl, "JPEG", slotX + 4, imgAreaY + 4, imgW, imgH);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(6.5);
      doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
      doc.text(label, slotX + slotW / 2, imgAreaY + imgH + 11, { align: "center" });
    }
  }

  // ── Radar panel (right column) ──
  const radarPanelH = contentBottom - contentTop;
  drawCard(doc, rightX, contentTop, rightW, radarPanelH);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Comprehensive analysis", rightX + 16, contentTop + 18);

  const radarPad = 12;
  const radarSize = Math.min(rightW - radarPad * 2, radarPanelH - 40);
  const radarX = rightX + (rightW - radarSize) / 2;
  const radarY = contentTop + 28;
  drawRadarChart(doc, data.radar, radarX, radarY, radarSize);
}

export async function generateSkinfitReportPdf(data: SdetectReportData): Promise<Buffer> {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 24;
  const logo = await loadHeaderLogo();
  const totalPages = 3;

  // ── Page 1 ──
  paintPageBackground(doc);
  drawHeader(doc, logo, "Skin Analysis Report", 1, totalPages);
  await drawPageOne(doc, data, pageW, pageH, margin);
  drawFooter(doc);

  // ── Page 2 ──
  doc.addPage();
  paintPageBackground(doc);
  drawHeader(doc, logo, "Clinical insights", 2, totalPages);

  let y = 74;
  const maxW = pageW - margin * 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Issue analysis", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...SKINFIT_REPORT_THEME.ink);
  for (const line of wrap(doc, data.issueAnalysis, maxW)) {
    if (y > pageH - 48) {
      doc.addPage();
      paintPageBackground(doc);
      drawHeader(doc, logo, "Clinical insights", 2, totalPages);
      y = 74;
    }
    doc.text(line, margin, y);
    y += 13;
  }

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Skincare advice", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  for (const [idx, advice] of data.skincareAdvice.entries()) {
    for (const line of wrap(doc, `${idx + 1}. ${advice}`, maxW)) {
      if (y > pageH - 48) {
        doc.addPage();
        paintPageBackground(doc);
        drawHeader(doc, logo, "Clinical insights", 2, totalPages);
        y = 74;
      }
      doc.text(line, margin, y);
      y += 13;
    }
    y += 4;
  }
  drawFooter(doc);

  // ── Page 3 ──
  doc.addPage();
  paintPageBackground(doc);
  drawHeader(doc, logo, "Grade analysis", 3, totalPages);

  const chartY = 78;
  const chartH = pageH - chartY - 52;
  const halfH = chartH / 2 - 6;
  drawLineChart(
    doc,
    "General analysis",
    data.generalAnalysis,
    margin,
    chartY,
    pageW - margin * 2,
    halfH
  );
  drawLineChart(
    doc,
    "In-depth analysis",
    data.inDepthAnalysis,
    margin,
    chartY + halfH + 18,
    pageW - margin * 2,
    halfH
  );
  drawFooter(doc);

  return Buffer.from(doc.output("arraybuffer"));
}
