import { readFile } from "node:fs/promises";
import path from "node:path";
import { jsPDF } from "jspdf";
import sharp from "sharp";
import { drawBarChart, drawRadarChart, SKINFIT_REPORT_THEME } from "./charts";
import type { SdetectReportData } from "./types";

let logoCache: string | null = null;

async function loadLogoDataUrl(): Promise<string> {
  if (logoCache) return logoCache;
  const svgPath = path.join(process.cwd(), "public/branding/skinfit-wellness-logo.svg");
  const svg = await readFile(svgPath);
  const png = await sharp(svg).resize({ width: 320 }).png().toBuffer();
  logoCache = `data:image/png;base64,${png.toString("base64")}`;
  return logoCache;
}

async function imageDataUrl(buffer: Buffer): Promise<string> {
  const jpg = await sharp(buffer).jpeg({ quality: 90 }).toBuffer();
  return `data:image/jpeg;base64,${jpg.toString("base64")}`;
}

function wrap(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text.replace(/\s+/g, " ").trim(), maxWidth);
}

function paintPageBackground(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFillColor(...SKINFIT_REPORT_THEME.pageBg);
  doc.rect(0, 0, w, h, "F");
}

function drawHeader(doc: jsPDF, logoDataUrl: string, title: string, pageNo: number, total: number) {
  const w = doc.internal.pageSize.getWidth();
  doc.setFillColor(...SKINFIT_REPORT_THEME.navy);
  doc.rect(0, 0, w, 52, "F");
  doc.addImage(logoDataUrl, "PNG", 28, 10, 118, 32);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(title, w / 2, 30, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(`${pageNo} / ${total}`, w - 28, 30, { align: "right" });
}

function drawFooter(doc: jsPDF) {
  const w = doc.internal.pageSize.getWidth();
  const h = doc.internal.pageSize.getHeight();
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
  doc.text(
    "Clinical reference only · Generated by SkinFit Wellness",
    w / 2,
    h - 16,
    { align: "center" }
  );
}

function drawSummaryCard(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string
) {
  doc.setFillColor(...SKINFIT_REPORT_THEME.card);
  doc.setDrawColor(...SKINFIT_REPORT_THEME.navyLight);
  doc.setLineWidth(0.8);
  doc.roundedRect(x, y, w, h, 6, 6, "FD");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
  doc.text(label, x + 12, y + 18);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text(value, x + 12, y + 40);
}

export async function generateSkinfitReportPdf(data: SdetectReportData): Promise<Buffer> {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 28;
  const logo = await loadLogoDataUrl();
  const totalPages = 3;

  // ── Page 1 ──
  paintPageBackground(doc);
  drawHeader(doc, logo, "Skin Analysis Report", 1, totalPages);

  const infoY = 68;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...SKINFIT_REPORT_THEME.ink);
  doc.text(`Name: ${data.patient.name}`, margin, infoY);
  doc.text(`Gender: ${data.patient.gender}`, margin + 170, infoY);
  doc.text(`Age: ${data.patient.age}`, margin + 320, infoY);
  doc.text(`Phone: ${data.patient.phone}`, margin + 400, infoY);
  doc.setFont("helvetica", "normal");
  doc.text(`Report date: ${data.patient.reportDate}`, margin, infoY + 16);
  doc.text(`Scan count: ${data.patient.scanFrequency}`, margin + 220, infoY + 16);

  const cardY = infoY + 34;
  const cardW = 118;
  const cardH = 54;
  drawSummaryCard(doc, margin, cardY, cardW, cardH, "Skin type", data.classification);
  drawSummaryCard(doc, margin + cardW + 10, cardY, cardW, cardH, "Moisture", `${data.moisture}%`);
  drawSummaryCard(
    doc,
    margin + (cardW + 10) * 2,
    cardY,
    cardW,
    cardH,
    "Overall score",
    String(data.comprehensiveScore)
  );

  if (data.faceImages) {
    const imgY = cardY + cardH + 14;
    const imgH = 118;
    const imgW = 88;
    const gap = 12;
    const labels: Array<[keyof typeof data.faceImages, string]> = [
      ["front", "Front (white map)"],
      ["left", "Left (natural)"],
      ["right", "Right (natural)"],
    ];
    let ix = margin;
    for (const [key, label] of labels) {
      const dataUrl = await imageDataUrl(data.faceImages[key]);
      doc.setFillColor(...SKINFIT_REPORT_THEME.card);
      doc.setDrawColor(...SKINFIT_REPORT_THEME.navyLight);
      doc.roundedRect(ix, imgY, imgW + 16, imgH + 28, 6, 6, "FD");
      doc.addImage(dataUrl, "JPEG", ix + 8, imgY + 8, imgW, imgH);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...SKINFIT_REPORT_THEME.muted);
      doc.text(label, ix + (imgW + 16) / 2, imgY + imgH + 20, { align: "center" });
      ix += imgW + 16 + gap;
    }
  }

  const radarX = pageW * 0.42;
  const radarY = cardY - 6;
  const radarSize = pageH - radarY - 42;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Comprehensive analysis", radarX + radarSize * 0.18, radarY - 4);
  drawRadarChart(doc, data.radar, radarX, radarY + 8, radarSize);
  drawFooter(doc);

  // ── Page 2 ──
  doc.addPage();
  paintPageBackground(doc);
  drawHeader(doc, logo, "Clinical insights", 2, totalPages);

  let y = 74;
  const maxW = pageW - margin * 2;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Issue analysis", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(...SKINFIT_REPORT_THEME.ink);
  for (const line of wrap(doc, data.issueAnalysis, maxW)) {
    if (y > pageH - 48) {
      doc.addPage();
      paintPageBackground(doc);
      drawHeader(doc, logo, "Clinical insights", 2, totalPages);
      y = 74;
    }
    doc.text(line, margin, y);
    y += 13;
  }

  y += 12;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...SKINFIT_REPORT_THEME.navy);
  doc.text("Skincare advice", margin, y);
  y += 18;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  for (const [idx, advice] of data.skincareAdvice.entries()) {
    for (const line of wrap(doc, `${idx + 1}. ${advice}`, maxW)) {
      if (y > pageH - 48) {
        doc.addPage();
        paintPageBackground(doc);
        drawHeader(doc, logo, "Clinical insights", 2, totalPages);
        y = 74;
      }
      doc.text(line, margin, y);
      y += 13;
    }
    y += 4;
  }
  drawFooter(doc);

  // ── Page 3 ──
  doc.addPage();
  paintPageBackground(doc);
  drawHeader(doc, logo, "Grade analysis", 3, totalPages);

  const chartY = 78;
  const chartH = pageH - chartY - 52;
  const halfH = chartH / 2 - 6;
  drawBarChart(
    doc,
    "General analysis",
    data.generalAnalysis,
    margin,
    chartY,
    pageW - margin * 2,
    halfH
  );
  drawBarChart(
    doc,
    "In-depth analysis",
    data.inDepthAnalysis,
    margin,
    chartY + halfH + 18,
    pageW - margin * 2,
    halfH
  );
  drawFooter(doc);

  return Buffer.from(doc.output("arraybuffer"));
}
