export const MEDICAL_DISCLAIMER_SHORT =
  "SkinFit provides educational skin insights and care coordination. It is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional for medical concerns.";

export const MEDICAL_DISCLAIMER_CAPTURE =
  "Scan results are educational only, not a medical diagnosis. Always consult a healthcare professional for medical advice or treatment.";

export const MEDICAL_DISCLAIMER_CHAT_AI =
  "For medical advice, diagnosis, or treatment, consult a qualified healthcare professional. AI responses are informational only.";

export const MEDICAL_DISCLAIMER_CHAT_DOCTOR =
  "Messages are not for emergencies. For urgent medical concerns, call your local emergency number.";

export function getWebPortalUrl(): string {
  return (
    process.env.EXPO_PUBLIC_WEB_PORTAL_URL?.replace(/\/$/, "") ??
    process.env.EXPO_PUBLIC_API_URL?.replace(/\/$/, "") ??
    ""
  );
}

export function scanReportDisclaimer(): string {
  return `© ${new Date().getFullYear()} SkinFit Wellness. All rights reserved. This diagnostic summary is generated by machine learning algorithms and does not substitute formal medical advice, diagnosis, or prescription. Always consult a qualified healthcare professional for medical concerns.`;
}
